"""Add email and phone columns to Ticket

Revision ID: 3725844ad225
Revises: ce81e00cd75a
Create Date: 2025-05-08 23:30:04.838277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3725844ad225'
down_revision = 'ce81e00cd75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('ticket', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'phone')
    op.drop_column('ticket', 'email')
    # ### end Alembic commands ###
